// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName             = "/routineops.AgentService/Connect"
	AgentService_AckTaskReceived_FullMethodName     = "/routineops.AgentService/AckTaskReceived"
	AgentService_ReportInventory_FullMethodName     = "/routineops.AgentService/ReportInventory"
	AgentService_ReportTaskResult_FullMethodName    = "/routineops.AgentService/ReportTaskResult"
	AgentService_ReportSecurityEvent_FullMethodName = "/routineops.AgentService/ReportSecurityEvent"
	AgentService_FetchPolicy_FullMethodName         = "/routineops.AgentService/FetchPolicy"
	AgentService_RequestAdminAccess_FullMethodName  = "/routineops.AgentService/RequestAdminAccess"
	AgentService_FetchAdminStatus_FullMethodName    = "/routineops.AgentService/FetchAdminStatus"
	AgentService_ReportAdminAccess_FullMethodName   = "/routineops.AgentService/ReportAdminAccess"
	AgentService_SubmitHelpRequest_FullMethodName   = "/routineops.AgentService/SubmitHelpRequest"
	AgentService_FetchScriptPolicies_FullMethodName = "/routineops.AgentService/FetchScriptPolicies"
	AgentService_ReportScriptResult_FullMethodName  = "/routineops.AgentService/ReportScriptResult"
	AgentService_ReportLockStatus_FullMethodName    = "/routineops.AgentService/ReportLockStatus"
	AgentService_FetchLockStatus_FullMethodName     = "/routineops.AgentService/FetchLockStatus"
	AgentService_EscrowRecoveryKey_FullMethodName   = "/routineops.AgentService/EscrowRecoveryKey"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Постоянный стрим: heartbeat → сервер, задачи ← сервер. (ADR-5)
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, Task], error)
	// Подтверждение доставки задачи агенту (до выполнения).
	AckTaskReceived(ctx context.Context, in *TaskReceivedAck, opts ...grpc.CallOption) (*TaskReceivedAckResponse, error)
	ReportInventory(ctx context.Context, in *InventoryReport, opts ...grpc.CallOption) (*InventoryAck, error)
	ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error)
	ReportSecurityEvent(ctx context.Context, in *SecurityEvent, opts ...grpc.CallOption) (*SecurityEventAck, error)
	// Синхронизация политик ПО (запрещённое/разрешённое) для Security Monitor.
	// Pull: агент тянет при старте; версия — unix max(updated_at) (см. FetchPolicyResponse).
	FetchPolicy(ctx context.Context, in *FetchPolicyRequest, opts ...grpc.CallOption) (*FetchPolicyResponse, error)
	// Временные права администратора (Этап 4). Одобрение IT-админом — через REST.
	RequestAdminAccess(ctx context.Context, in *RequestAdminAccessRequest, opts ...grpc.CallOption) (*RequestAdminAccessResponse, error)
	FetchAdminStatus(ctx context.Context, in *FetchAdminStatusRequest, opts ...grpc.CallOption) (*FetchAdminStatusResponse, error)
	ReportAdminAccess(ctx context.Context, in *ReportAdminAccessRequest, opts ...grpc.CallOption) (*ReportAdminAccessResponse, error)
	// Обращение за помощью с устройства (текст + опциональный скриншот).
	// Закрытие IT-админом — через REST, как admin-access-requests.
	SubmitHelpRequest(ctx context.Context, in *SubmitHelpRequestRequest, opts ...grpc.CallOption) (*SubmitHelpRequestResponse, error)
	// Скрипт-политики (Этап 5). Pull эффективного набора + отчёт о выполнении
	// (как FetchPolicy + ReportTaskResult).
	FetchScriptPolicies(ctx context.Context, in *FetchScriptPoliciesRequest, opts ...grpc.CallOption) (*FetchScriptPoliciesResponse, error)
	ReportScriptResult(ctx context.Context, in *ScriptResult, opts ...grpc.CallOption) (*ScriptResultAck, error)
	// Блокировка устройства: агент подтверждает применение/снятие (аудит + UI).
	ReportLockStatus(ctx context.Context, in *ReportLockStatusRequest, opts ...grpc.CallOption) (*ReportLockStatusResponse, error)
	// Реконсиляция блокировки (pull): переживает потерю push-команды и ребут —
	// Task.lock едет РАЗ по Connect-стриму, сверки нет, поэтому после рестарта
	// агента desired-состояние сервера может разойтись с локальным lock.json.
	// Агент периодически сверяет их (как FetchAdminStatus).
	FetchLockStatus(ctx context.Context, in *FetchLockStatusRequest, opts ...grpc.CallOption) (*FetchLockStatusResponse, error)
	// Эскроу recovery-ключа FileVault (enterprise). СИНХРОННЫЙ: stored=true ТОЛЬКО
	// после устойчивого сохранения. Реальная ошибка (Unavailable/FailedPrecondition) —
	// агент ретраит и НЕ запускает деструктив, если escrow не подтверждён. НЕ через outbox.
	EscrowRecoveryKey(ctx context.Context, in *EscrowRecoveryKeyRequest, opts ...grpc.CallOption) (*EscrowRecoveryKeyResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, Task]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.BidiStreamingClient[HeartbeatRequest, Task]

func (c *agentServiceClient) AckTaskReceived(ctx context.Context, in *TaskReceivedAck, opts ...grpc.CallOption) (*TaskReceivedAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskReceivedAckResponse)
	err := c.cc.Invoke(ctx, AgentService_AckTaskReceived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportInventory(ctx context.Context, in *InventoryReport, opts ...grpc.CallOption) (*InventoryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryAck)
	err := c.cc.Invoke(ctx, AgentService_ReportInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultAck)
	err := c.cc.Invoke(ctx, AgentService_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportSecurityEvent(ctx context.Context, in *SecurityEvent, opts ...grpc.CallOption) (*SecurityEventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityEventAck)
	err := c.cc.Invoke(ctx, AgentService_ReportSecurityEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FetchPolicy(ctx context.Context, in *FetchPolicyRequest, opts ...grpc.CallOption) (*FetchPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPolicyResponse)
	err := c.cc.Invoke(ctx, AgentService_FetchPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RequestAdminAccess(ctx context.Context, in *RequestAdminAccessRequest, opts ...grpc.CallOption) (*RequestAdminAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAdminAccessResponse)
	err := c.cc.Invoke(ctx, AgentService_RequestAdminAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FetchAdminStatus(ctx context.Context, in *FetchAdminStatusRequest, opts ...grpc.CallOption) (*FetchAdminStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchAdminStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_FetchAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportAdminAccess(ctx context.Context, in *ReportAdminAccessRequest, opts ...grpc.CallOption) (*ReportAdminAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAdminAccessResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportAdminAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubmitHelpRequest(ctx context.Context, in *SubmitHelpRequestRequest, opts ...grpc.CallOption) (*SubmitHelpRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitHelpRequestResponse)
	err := c.cc.Invoke(ctx, AgentService_SubmitHelpRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FetchScriptPolicies(ctx context.Context, in *FetchScriptPoliciesRequest, opts ...grpc.CallOption) (*FetchScriptPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchScriptPoliciesResponse)
	err := c.cc.Invoke(ctx, AgentService_FetchScriptPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportScriptResult(ctx context.Context, in *ScriptResult, opts ...grpc.CallOption) (*ScriptResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScriptResultAck)
	err := c.cc.Invoke(ctx, AgentService_ReportScriptResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportLockStatus(ctx context.Context, in *ReportLockStatusRequest, opts ...grpc.CallOption) (*ReportLockStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLockStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportLockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FetchLockStatus(ctx context.Context, in *FetchLockStatusRequest, opts ...grpc.CallOption) (*FetchLockStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchLockStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_FetchLockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EscrowRecoveryKey(ctx context.Context, in *EscrowRecoveryKeyRequest, opts ...grpc.CallOption) (*EscrowRecoveryKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscrowRecoveryKeyResponse)
	err := c.cc.Invoke(ctx, AgentService_EscrowRecoveryKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Постоянный стрим: heartbeat → сервер, задачи ← сервер. (ADR-5)
	Connect(grpc.BidiStreamingServer[HeartbeatRequest, Task]) error
	// Подтверждение доставки задачи агенту (до выполнения).
	AckTaskReceived(context.Context, *TaskReceivedAck) (*TaskReceivedAckResponse, error)
	ReportInventory(context.Context, *InventoryReport) (*InventoryAck, error)
	ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error)
	ReportSecurityEvent(context.Context, *SecurityEvent) (*SecurityEventAck, error)
	// Синхронизация политик ПО (запрещённое/разрешённое) для Security Monitor.
	// Pull: агент тянет при старте; версия — unix max(updated_at) (см. FetchPolicyResponse).
	FetchPolicy(context.Context, *FetchPolicyRequest) (*FetchPolicyResponse, error)
	// Временные права администратора (Этап 4). Одобрение IT-админом — через REST.
	RequestAdminAccess(context.Context, *RequestAdminAccessRequest) (*RequestAdminAccessResponse, error)
	FetchAdminStatus(context.Context, *FetchAdminStatusRequest) (*FetchAdminStatusResponse, error)
	ReportAdminAccess(context.Context, *ReportAdminAccessRequest) (*ReportAdminAccessResponse, error)
	// Обращение за помощью с устройства (текст + опциональный скриншот).
	// Закрытие IT-админом — через REST, как admin-access-requests.
	SubmitHelpRequest(context.Context, *SubmitHelpRequestRequest) (*SubmitHelpRequestResponse, error)
	// Скрипт-политики (Этап 5). Pull эффективного набора + отчёт о выполнении
	// (как FetchPolicy + ReportTaskResult).
	FetchScriptPolicies(context.Context, *FetchScriptPoliciesRequest) (*FetchScriptPoliciesResponse, error)
	ReportScriptResult(context.Context, *ScriptResult) (*ScriptResultAck, error)
	// Блокировка устройства: агент подтверждает применение/снятие (аудит + UI).
	ReportLockStatus(context.Context, *ReportLockStatusRequest) (*ReportLockStatusResponse, error)
	// Реконсиляция блокировки (pull): переживает потерю push-команды и ребут —
	// Task.lock едет РАЗ по Connect-стриму, сверки нет, поэтому после рестарта
	// агента desired-состояние сервера может разойтись с локальным lock.json.
	// Агент периодически сверяет их (как FetchAdminStatus).
	FetchLockStatus(context.Context, *FetchLockStatusRequest) (*FetchLockStatusResponse, error)
	// Эскроу recovery-ключа FileVault (enterprise). СИНХРОННЫЙ: stored=true ТОЛЬКО
	// после устойчивого сохранения. Реальная ошибка (Unavailable/FailedPrecondition) —
	// агент ретраит и НЕ запускает деструктив, если escrow не подтверждён. НЕ через outbox.
	EscrowRecoveryKey(context.Context, *EscrowRecoveryKeyRequest) (*EscrowRecoveryKeyResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(grpc.BidiStreamingServer[HeartbeatRequest, Task]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) AckTaskReceived(context.Context, *TaskReceivedAck) (*TaskReceivedAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckTaskReceived not implemented")
}
func (UnimplementedAgentServiceServer) ReportInventory(context.Context, *InventoryReport) (*InventoryAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInventory not implemented")
}
func (UnimplementedAgentServiceServer) ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedAgentServiceServer) ReportSecurityEvent(context.Context, *SecurityEvent) (*SecurityEventAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSecurityEvent not implemented")
}
func (UnimplementedAgentServiceServer) FetchPolicy(context.Context, *FetchPolicyRequest) (*FetchPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPolicy not implemented")
}
func (UnimplementedAgentServiceServer) RequestAdminAccess(context.Context, *RequestAdminAccessRequest) (*RequestAdminAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAdminAccess not implemented")
}
func (UnimplementedAgentServiceServer) FetchAdminStatus(context.Context, *FetchAdminStatusRequest) (*FetchAdminStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAdminStatus not implemented")
}
func (UnimplementedAgentServiceServer) ReportAdminAccess(context.Context, *ReportAdminAccessRequest) (*ReportAdminAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAdminAccess not implemented")
}
func (UnimplementedAgentServiceServer) SubmitHelpRequest(context.Context, *SubmitHelpRequestRequest) (*SubmitHelpRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHelpRequest not implemented")
}
func (UnimplementedAgentServiceServer) FetchScriptPolicies(context.Context, *FetchScriptPoliciesRequest) (*FetchScriptPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchScriptPolicies not implemented")
}
func (UnimplementedAgentServiceServer) ReportScriptResult(context.Context, *ScriptResult) (*ScriptResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportScriptResult not implemented")
}
func (UnimplementedAgentServiceServer) ReportLockStatus(context.Context, *ReportLockStatusRequest) (*ReportLockStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLockStatus not implemented")
}
func (UnimplementedAgentServiceServer) FetchLockStatus(context.Context, *FetchLockStatusRequest) (*FetchLockStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchLockStatus not implemented")
}
func (UnimplementedAgentServiceServer) EscrowRecoveryKey(context.Context, *EscrowRecoveryKeyRequest) (*EscrowRecoveryKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EscrowRecoveryKey not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&grpc.GenericServerStream[HeartbeatRequest, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.BidiStreamingServer[HeartbeatRequest, Task]

func _AgentService_AckTaskReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReceivedAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AckTaskReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AckTaskReceived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AckTaskReceived(ctx, req.(*TaskReceivedAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportInventory(ctx, req.(*InventoryReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportSecurityEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportSecurityEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportSecurityEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportSecurityEvent(ctx, req.(*SecurityEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FetchPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FetchPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FetchPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FetchPolicy(ctx, req.(*FetchPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RequestAdminAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAdminAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RequestAdminAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RequestAdminAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RequestAdminAccess(ctx, req.(*RequestAdminAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FetchAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAdminStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FetchAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FetchAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FetchAdminStatus(ctx, req.(*FetchAdminStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportAdminAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAdminAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportAdminAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportAdminAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportAdminAccess(ctx, req.(*ReportAdminAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubmitHelpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHelpRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitHelpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitHelpRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitHelpRequest(ctx, req.(*SubmitHelpRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FetchScriptPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchScriptPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FetchScriptPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FetchScriptPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FetchScriptPolicies(ctx, req.(*FetchScriptPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportScriptResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScriptResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportScriptResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportScriptResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportScriptResult(ctx, req.(*ScriptResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportLockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLockStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportLockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportLockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportLockStatus(ctx, req.(*ReportLockStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FetchLockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLockStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FetchLockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FetchLockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FetchLockStatus(ctx, req.(*FetchLockStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_EscrowRecoveryKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscrowRecoveryKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).EscrowRecoveryKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_EscrowRecoveryKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).EscrowRecoveryKey(ctx, req.(*EscrowRecoveryKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routineops.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AckTaskReceived",
			Handler:    _AgentService_AckTaskReceived_Handler,
		},
		{
			MethodName: "ReportInventory",
			Handler:    _AgentService_ReportInventory_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _AgentService_ReportTaskResult_Handler,
		},
		{
			MethodName: "ReportSecurityEvent",
			Handler:    _AgentService_ReportSecurityEvent_Handler,
		},
		{
			MethodName: "FetchPolicy",
			Handler:    _AgentService_FetchPolicy_Handler,
		},
		{
			MethodName: "RequestAdminAccess",
			Handler:    _AgentService_RequestAdminAccess_Handler,
		},
		{
			MethodName: "FetchAdminStatus",
			Handler:    _AgentService_FetchAdminStatus_Handler,
		},
		{
			MethodName: "ReportAdminAccess",
			Handler:    _AgentService_ReportAdminAccess_Handler,
		},
		{
			MethodName: "SubmitHelpRequest",
			Handler:    _AgentService_SubmitHelpRequest_Handler,
		},
		{
			MethodName: "FetchScriptPolicies",
			Handler:    _AgentService_FetchScriptPolicies_Handler,
		},
		{
			MethodName: "ReportScriptResult",
			Handler:    _AgentService_ReportScriptResult_Handler,
		},
		{
			MethodName: "ReportLockStatus",
			Handler:    _AgentService_ReportLockStatus_Handler,
		},
		{
			MethodName: "FetchLockStatus",
			Handler:    _AgentService_FetchLockStatus_Handler,
		},
		{
			MethodName: "EscrowRecoveryKey",
			Handler:    _AgentService_EscrowRecoveryKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
